Repository team-peekabook/Peekabook-iOS, pull requests merged in 2023-05, with the labels that each got.

#232 [Feat] #231 - 로그인로직수정
  Peekabook/Peekabook.xcodeproj/project.pbxproj
  Peekabook/Peekabook/Application/AppDelegate.swift
  Peekabook/Peekabook/Application/SceneDelegate.swift
  Peekabook/Peekabook/Network/API/AuthAPI.swift
  Peekabook/Peekabook/Network/DTO/Auth/GetUpdatedTokenResponse.swift
  Peekabook/Peekabook/Network/DTO/Auth/SocialLoginResponse.swift
  Peekabook/Peekabook/Network/Foundation/MoyaLoggerPlugin.swift
  Peekabook/Peekabook/Network/Foundation/NetworkConstant.swift
  Peekabook/Peekabook/Network/Foundation/UserDefaultsKey.swift
  Peekabook/Peekabook/Network/Foundation/UserManager.swift
  Peekabook/Peekabook/Network/Router/AuthRouter.swift
  Peekabook/Peekabook/Presentation/Auth/VC/LoginVC.swift
  Peekabook/Peekabook/Presentation/Auth/VC/SignUpVC.swift
  Peekabook/Peekabook/Presentation/BookShelf/VC/BookShelfVC.swift
  Peekabook/Peekabook/Presentation/MyPage/VC/DeleteAccountPopUpVC.swift
Labels: 인영 💛, 두영 🤎, API 📡

#238 [Feat] #235 - 차단 유저 조회, 차단한 유저 차단해제 API 연결
  Peekabook/Peekabook.xcodeproj/project.pbxproj
  Peekabook/Peekabook/Network/API/MyPageAPI.swift
  Peekabook/Peekabook/Network/DTO/MyPage/GetAccountResponse.swift
  Peekabook/Peekabook/Network/DTO/MyPage/GetBlockedAccountResponse.swift
  Peekabook/Peekabook/Network/Router/MyPageRouter.swift
  Peekabook/Peekabook/Presentation/MyPage/VC/ManageBlockUsersVC.swift
  Peekabook/Peekabook/Presentation/MyPage/VC/UnblockPopUpVC.swift
  Peekabook/Peekabook/Presentation/MyPage/Views/BlockedUserCVC.swift
Labels: 수빈 🤍, API 📡

#241 [Chore] #206 - 프로필사진 수정 시 Alert 액션 수정 및 Tapgesture 적용
  Peekabook/Peekabook/Presentation/Auth/VC/SignUpVC.swift
  Peekabook/Peekabook/Presentation/MyPage/VC/EditMyProfileVC.swift
Labels: 인영 💛, Design 🎨

#250 [Chore] #249 - 레이아웃 수정
  Peekabook/Peekabook.xcodeproj/project.pbxproj
  Peekabook/Peekabook/Global/Literals/StringLiterals.swift
  Peekabook/Peekabook/Presentation/AddBook/VC/BookSearchVC.swift
  Peekabook/Peekabook/Presentation/BookDetail/VC/BookDetailVC.swift
  Peekabook/Peekabook/Presentation/BookDetail/VC/EditBookVC.swift
  Peekabook/Peekabook/Presentation/BookShelf/VC/BookShelfVC.swift
  Peekabook/Peekabook/Presentation/MyNotification/Model/NotificationModel.swift
  Peekabook/Peekabook/Presentation/MyNotification/VC/MyNotificationVC.swift
  Peekabook/Peekabook/Presentation/MyPage/VC/EditMyProfileVC.swift
  Peekabook/Peekabook/Presentation/UIComponents/CustomNavigationBar.swift
Labels: 수빈 🤍, Design 🎨, Fix ✨

#255 [Fix] #252 - placeholder 이슈 해결
  Peekabook/Peekabook/Presentation/BookDetail/VC/EditBookVC.swift
Labels: 두영 🤎, Fix ✨

#257 [Fix] #256 - QA 반영
  Peekabook/Peekabook/Presentation/AddBook/VC/ErrorPopUpVC.swift
  Peekabook/Peekabook/Presentation/UIComponents/CustomTextView.swift
Labels: 두영 🤎, Fix ✨

#258 [Fix] #251 - 프로필 에러 수정
  Peekabook/Peekabook/Presentation/MyPage/VC/EditMyProfileVC.swift
  Peekabook/Peekabook/Presentation/MyPage/VC/MyPageVC.swift
  Peekabook/Peekabook/Presentation/MyPage/Views/MyPageHeaderView.swift
  Peekabook/Peekabook/Presentation/UIComponents/CustomNavigationBar.swift
Labels: 인영 💛, API 📡, Fix ✨
