Repository team-peekabook/Peekabook-iOS, pull requests merged in 2023-01, with the labels that each got.

#10 [Feat] #9 - 책 등록 뷰 레이아웃
  Peekabook/Peekabook/Presentation/AddBook/VC/AddBookVC.swift
Labels: 두영 🎄, Design 🎨

#17 [Fix] #15 - 책 추천뷰 이름변경
  Peekabook/Peekabook.xcodeproj/project.pbxproj
  Peekabook/Peekabook/Presentation/Proposal/VC/ConfirmPopUpViewController.swift
  Peekabook/Peekabook/Presentation/Proposal/VC/ProposalVC.swift
  Peekabook/Peekabook/Presentation/Proposal/Views/.gitkeep
  Peekabook/Peekabook/Presentation/Proposal/Views/.gitkeep.md
  Peekabook/Peekabook/Presentation/Proposal/Views/.gitkeep.xib
  Peekabook/Peekabook/Presentation/Recommend/VC/RecommendVC.swift
Labels: 두영 🎄, Fix ✨

#12 [Feat] #7- 추천뷰레이아웃구현
  Peekabook/Peekabook.xcodeproj/project.pbxproj
  Peekabook/Peekabook/Presentation/Recommend/RecommendModel.swift
  Peekabook/Peekabook/Presentation/Recommend/VC/RecommendCollectionViewCell.swift
  Peekabook/Peekabook/Presentation/Recommend/VC/RecommendTableViewCell.swift
  Peekabook/Peekabook/Presentation/Recommend/VC/RecommendVC.swift
  Peekabook/Peekabook/Presentation/Recommend/VC/RecommendedVC.swift
  Peekabook/Peekabook/Presentation/Recommend/VC/RecommendingVC.swift
Labels: 인영 🧸, Design 🎨

#20 [Feat] #8 - 책장 뷰 레이아웃 구현
  Peekabook/.swiftlint.yml
  Peekabook/Peekabook.xcodeproj/project.pbxproj
  Peekabook/Peekabook/Application/AppDelegate.swift
  Peekabook/Peekabook/Global/Literals/FontLiterals.swift
  Peekabook/Peekabook/Global/Literals/ImageLiterals.swift
  Peekabook/Peekabook/Global/Literals/StringLiterals.swift
  Peekabook/Peekabook/Global/Utils/addSubviews.swift
  Peekabook/Peekabook/Presentation/BookShelf/Model/SampleBookModel.swift
  Peekabook/Peekabook/Presentation/BookShelf/Model/SampleFriendsModel.swift
  Peekabook/Peekabook/Presentation/BookShelf/Model/SamplePickModel.swift
  Peekabook/Peekabook/Presentation/BookShelf/Model/SampleUserModel.swift
  Peekabook/Peekabook/Presentation/BookShelf/VC/BookShelfVC.swift
  Peekabook/Peekabook/Presentation/BookShelf/VC/BottomBookShelfVC.swift
  Peekabook/Peekabook/Presentation/BookShelf/Views/.gitkeep
  Peekabook/Peekabook/Presentation/BookShelf/Views/CVC/BookShelfCVC.swift
  Peekabook/Peekabook/Presentation/BookShelf/Views/CVC/FriendsCVC.swift
  Peekabook/Peekabook/Presentation/BookShelf/Views/CVC/PickCVC.swift
  Peekabook/Peekabook/Presentation/MyPage/VC/MyPageVC.swift
  Peekabook/Peekabook/Presentation/UIComponents/DoubleBottomLineView.swift
  Peekabook/Peekabook/Presentation/UIComponents/DoubleHeaderLineView.swift
Labels: 수빈 💨, Design 🎨

#24 [Feat] #19 - 책 검색뷰 레이아웃
  Peekabook/Peekabook.xcodeproj/project.pbxproj
  Peekabook/Peekabook/Global/Literals/ImageLiterals.swift
  Peekabook/Peekabook/Global/Literals/StringLiterals.swift
  Peekabook/Peekabook/Global/Resources/Assets.xcassets/icons/icn_plus_mini.imageset/Contents.json
  Peekabook/Peekabook/Global/Resources/Assets.xcassets/icons/icn_plus_mini.imageset/icn_plus_mini.png
  Peekabook/Peekabook/Global/Resources/Assets.xcassets/icons/icn_plus_mini.imageset/icn_plus_mini@2x.png
  Peekabook/Peekabook/Global/Resources/Assets.xcassets/icons/icn_plus_mini.imageset/icn_plus_mini@3x.png
  Peekabook/Peekabook/Global/Resources/Assets.xcassets/icons/icn_search.imageset/Contents.json
  Peekabook/Peekabook/Global/Resources/Assets.xcassets/icons/icn_search.imageset/icn_search.png
  Peekabook/Peekabook/Global/Resources/Assets.xcassets/icons/icn_search.imageset/icn_search@2x.png
  Peekabook/Peekabook/Global/Resources/Assets.xcassets/icons/icn_search.imageset/icn_search@3x.png
  Peekabook/Peekabook/Presentation/AddBook/BookInfoModel.swift
  Peekabook/Peekabook/Presentation/AddBook/VC/BookInfoTableViewCell.swift
  Peekabook/Peekabook/Presentation/AddBook/VC/BookSearchVC.swift
Labels: 두영 🎄, Design 🎨

#23 [Feat] #16- 사용자검색뷰레이아웃구현
  Peekabook/Peekabook.xcodeproj/project.pbxproj
  Peekabook/Peekabook.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Peekabook/Peekabook/Application/SceneDelegate.swift
  Peekabook/Peekabook/Presentation/UserSearch/VC/UserSearchModel.swift
  Peekabook/Peekabook/Presentation/UserSearch/VC/UserSearchTableViewCell.swift
  Peekabook/Peekabook/Presentation/UserSearch/VC/UserSearchVC.swift
Labels: 인영 🧸, Design 🎨

#27 [Fix] #26- 프로젝트 경로 충돌 해결
  Peekabook/Peekabook.xcodeproj/project.pbxproj
  Peekabook/Peekabook.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Peekabook/Peekabook/Application/SceneDelegate.swift
Labels: 인영 🧸, Fix ✨

#29 [Chore] #28 - 사용자검색 코드리뷰 반영
  Peekabook/Peekabook.xcodeproj/project.pbxproj
  Peekabook/Peekabook/Info.plist
  Peekabook/Peekabook/Presentation/AddBook/Model/BookInfoModel.swift
  Peekabook/Peekabook/Presentation/AddBook/Views/.gitkeep
  Peekabook/Peekabook/Presentation/AddBook/Views/BookInfoTableViewCell.swift
  Peekabook/Peekabook/Presentation/UserSearch/Model/UserSearchModel.swift
  Peekabook/Peekabook/Presentation/UserSearch/VC/UserSearchVC.swift
  Peekabook/Peekabook/Presentation/UserSearch/Views/.gitkeep
  Peekabook/Peekabook/Presentation/UserSearch/Views/UserSearchTVC.swift
Labels: 인영 🧸, Refactor 🔨

#31 [Feat] #25 - 바코드 스캔뷰
  Peekabook/Peekabook.xcodeproj/project.pbxproj
  Peekabook/Peekabook/Application/AppDelegate.swift
  Peekabook/Peekabook/Global/Literals/ImageLiterals.swift
  Peekabook/Peekabook/Global/Resources/Assets.xcassets/icons/icn_emptyView.imageset/Contents.json
  Peekabook/Peekabook/Global/Resources/Assets.xcassets/icons/icn_emptyView.imageset/icn_emptyView.png
  Peekabook/Peekabook/Global/Resources/Assets.xcassets/icons/icn_emptyView.imageset/icn_emptyView@2x.png
  Peekabook/Peekabook/Global/Resources/Assets.xcassets/icons/icn_emptyView.imageset/icn_emptyView@3x.png
  Peekabook/Peekabook/Info.plist
  Peekabook/Peekabook/Presentation/AddBook/VC/AddBookVC.swift
  Peekabook/Peekabook/Presentation/AddBook/VC/BarcodeViewController.swift
  Peekabook/Peekabook/Presentation/AddBook/VC/BookInfoTableViewCell.swift
  Peekabook/Peekabook/Presentation/BookShelf/VC/BottomBookShelfVC.swift
  Peekabook/Peekabook/Presentation/Recommend/VC/RecommendTableViewCell.swift
Labels: 두영 🎄, Design 🎨

#35 [Fix] #33- 책장 바텀 뷰 내부 컬랙션 뷰 스크롤 안되는 버그 수정
  Peekabook/Peekabook/Presentation/BookShelf/VC/BottomBookShelfVC.swift
Labels: 수빈 💨, Fix ✨

#42 [Feat] #36- 네트워크 세팅 및 샘플 코드(내 책장 뷰 조회하기) 추가
  Peekabook/Peekabook.xcodeproj/project.pbxproj
  Peekabook/Peekabook/Network/API/BookShelfAPI.swift
  Peekabook/Peekabook/Network/Base/.gitkeep
  Peekabook/Peekabook/Network/DTO/.gitkeep
  Peekabook/Peekabook/Network/DTO/BookShelf/MyBookShelfResponse.swift
  Peekabook/Peekabook/Network/Foundation/GeneralResponse.swift
  Peekabook/Peekabook/Network/Foundation/MoyaLoggerPlugin.swift
  Peekabook/Peekabook/Network/Foundation/NetworkConstant.swift
  Peekabook/Peekabook/Network/Foundation/NetworkResult.swift
  Peekabook/Peekabook/Network/Foundation/URLConstant.swift
  Peekabook/Peekabook/Network/Foundation/UserDefaultsKey.swift
  Peekabook/Peekabook/Network/Router/.gitkeep
  Peekabook/Peekabook/Network/Router/BookShelfRouter.swift
  Peekabook/Peekabook/Presentation/BookShelf/VC/BookShelfVC.swift
Labels: 수빈 💨, Setting ⚙️, API 📡

#40 [Feat] #30 - 알림 뷰 레이아웃 구현
  Peekabook/Peekabook.xcodeproj/project.pbxproj
  Peekabook/Peekabook/Global/Literals/StringLiterals.swift
  Peekabook/Peekabook/Presentation/MyNotification/NotificationModel.swift
  Peekabook/Peekabook/Presentation/MyNotification/VC/MyNotificationVC.swift
  Peekabook/Peekabook/Presentation/MyNotification/Views/MyNotificationTVC.swift
Labels: 인영 🧸, Design 🎨

#45 [Fix] #41 - 키보드 뷰 수정
  Peekabook/Peekabook/Presentation/AddBook/VC/AddBookVC.swift
  Peekabook/Peekabook/Presentation/AddBook/VC/BookSearchVC.swift
  Peekabook/Peekabook/Presentation/BookDetail/VC/EditBookVC.swift
Labels: 두영 🎄, Fix ✨

#47 [Chore] #46- 알림 뷰 유저 이름 굵기 변경
  Peekabook/Peekabook.xcodeproj/project.pbxproj
  Peekabook/Peekabook/Presentation/MyNotification/Model/NotificationModel.swift
  Peekabook/Peekabook/Presentation/MyNotification/VC/MyNotificationVC.swift
  Peekabook/Peekabook/Presentation/MyNotification/Views/MyNotificationTVC.swift
Labels: 인영 🧸, Refactor 🔨

#51 [Chore] #39 - 바코드 스캔 뷰 커스텀
  Peekabook/Peekabook.xcodeproj/project.pbxproj
  Peekabook/Peekabook/Global/Extension/UIButton+.swift
  Peekabook/Peekabook/Global/Literals/StringLiterals.swift
  Peekabook/Peekabook/Presentation/AddBook/VC/BarcodeViewController.swift
  Peekabook/Peekabook/Presentation/AddBook/VC/BookSearchVC.swift
  Peekabook/Peekabook/Presentation/AddBook/VC/ErrorPopUpViewController.swift
Labels: 두영 🎄, Design 🎨, Fix ✨

#54 [Chore] #52- 알림뷰레이아웃수정
  Peekabook/Peekabook/Presentation/MyNotification/Model/NotificationModel.swift
  Peekabook/Peekabook/Presentation/MyNotification/VC/MyNotificationVC.swift
  Peekabook/Peekabook/Presentation/MyNotification/Views/MyNotificationTVC.swift
Labels: 인영 🧸, Design 🎨

#56 [Refactor] #53 - 레이아웃 리팩토링
  Peekabook/Peekabook.xcodeproj/project.pbxproj
  Peekabook/Peekabook/Global/Extension/UITextField+.swift
  Peekabook/Peekabook/Global/Literals/StringLiterals.swift
  Peekabook/Peekabook/Presentation/AddBook/VC/AddBookVC.swift
  Peekabook/Peekabook/Presentation/AddBook/VC/BookEmptyViewController.swift
  Peekabook/Peekabook/Presentation/AddBook/VC/BookInfoTableViewCell.swift
  Peekabook/Peekabook/Presentation/AddBook/VC/BookSearchVC.swift
  Peekabook/Peekabook/Presentation/AddBook/VC/ErrorPopUpViewController.swift
  Peekabook/Peekabook/Presentation/BookDetail/VC/EditBookVC.swift
  Peekabook/Peekabook/Presentation/Proposal/VC/ConfirmPopUpViewController.swift
  Peekabook/Peekabook/Presentation/Proposal/VC/ProposalVC.swift
Labels: 두영 🎄, Refactor 🔨, Fix ✨

#59 [Chore] #58- Base URL 변경
  Peekabook/Peekabook/Network/Foundation/URLConstant.swift
Labels: 수빈 💨, Setting ⚙️, API 📡

#64 [Chore] #63 - 레이아웃 리팩토링
  Peekabook/Peekabook/Presentation/BookShelf/VC/BookShelfVC.swift
  Peekabook/Peekabook/Presentation/MyNotification/VC/MyNotificationVC.swift
  Peekabook/Peekabook/Presentation/MyNotification/Views/MyNotificationTVC.swift
  Peekabook/Peekabook/Presentation/Recommend/VC/RecommendVC.swift
  Peekabook/Peekabook/Presentation/Recommend/VC/RecommendedVC.swift
  Peekabook/Peekabook/Presentation/Recommend/VC/RecommendingVC.swift
  Peekabook/Peekabook/Presentation/Recommend/Views/RecommendTVC.swift
Labels: 인영 🧸, Refactor 🔨

#65 [Feat] #50 - 개발자 계정 등록 및 Config 파일 생성
  .gitignore
  Peekabook/Peekabook.xcodeproj/project.pbxproj
  Peekabook/Peekabook/Network/Foundation/URLConstant.swift
  Peekabook/Peekabook/Network/Router/AlarmRouter.swift
  Peekabook/Peekabook/Network/Router/BookShelfRouter.swift
  Peekabook/Peekabook/Network/Router/FriendRouter.swift
  Peekabook/Peekabook/Network/Router/PickRouter.swift
  Peekabook/Peekabook/Network/Router/RecommendRouter.swift
Labels: 수빈 💨, Setting ⚙️, API 📡

#72 [Feat] #43 - 상세보기 뷰 레이아웃 구현
  Peekabook/Peekabook.xcodeproj/project.pbxproj
  Peekabook/Peekabook/Global/Literals/StringLiterals.swift
  Peekabook/Peekabook/Presentation/BookDetail/VC/BookDetailVC.swift
  Peekabook/Peekabook/Presentation/BookDetail/VC/EditBookVC.swift
  Peekabook/Peekabook/Presentation/BookShelf/VC/BookShelfVC.swift
  Peekabook/Peekabook/Presentation/BookShelf/VC/BottomBookShelfVC.swift
Labels: 수빈 💭, Design 🎨

#75 [Chore] #68 - 메인 뷰 조회 API 샘플 코드 수정
  Peekabook/Peekabook/Network/API/BookShelfAPI.swift
  Peekabook/Peekabook/Network/DTO/BookShelf/MyBookShelfResponse.swift
  Peekabook/Peekabook/Presentation/BookShelf/VC/BookShelfVC.swift
Labels: 수빈 💭, API 📡

#76 [Feat] #68- 내 책장 (메인 뷰) 조회 서버 연결
  Peekabook/Peekabook/Presentation/BookShelf/VC/BookShelfVC.swift
  Peekabook/Peekabook/Presentation/BookShelf/VC/BottomBookShelfVC.swift
  Peekabook/Peekabook/Presentation/BookShelf/Views/CVC/BookShelfCVC.swift
  Peekabook/Peekabook/Presentation/BookShelf/Views/CVC/FriendsCVC.swift
  Peekabook/Peekabook/Presentation/BookShelf/Views/CVC/PickCVC.swift
  Peekabook/Peekabook/Presentation/TabBar/TabBarController.swift
Labels: 수빈 💭, API 📡

#78 [Feat] #71- 사용자 검색 API 연결
  Peekabook/Peekabook.xcodeproj/project.pbxproj
  Peekabook/Peekabook/Network/API/FriendAPI.swift
  Peekabook/Peekabook/Network/DTO/Friend/SearchUserResponse.swift
  Peekabook/Peekabook/Network/Router/FriendRouter.swift
  Peekabook/Peekabook/Presentation/UserSearch/VC/UserSearchVC.swift
  Peekabook/Peekabook/Presentation/UserSearch/Views/UserSearchTVC.swift
Labels: 인영 🧸, API 📡

#81 [Feat]#79 - 친구 팔로우 api 연결
  Peekabook/Peekabook/Network/API/FriendAPI.swift
  Peekabook/Peekabook/Network/Router/FriendRouter.swift
  Peekabook/Peekabook/Presentation/UserSearch/VC/UserSearchVC.swift
Labels: 인영 🧸, API 📡

#84 [Feat] #77- 친구 책장 뷰 서버 연결
  Peekabook/Peekabook.xcodeproj/project.pbxproj
  Peekabook/Peekabook/Global/Literals/StringLiterals.swift
  Peekabook/Peekabook/Network/API/BookShelfAPI.swift
  Peekabook/Peekabook/Network/DTO/BookShelf/FriendBookShelfResponse.swift
  Peekabook/Peekabook/Network/DTO/BookShelf/MyBookShelfResponse.swift
  Peekabook/Peekabook/Network/Router/BookShelfRouter.swift
  Peekabook/Peekabook/Presentation/BookShelf/VC/BookShelfVC.swift
  Peekabook/Peekabook/Presentation/BookShelf/VC/BottomBookShelfVC.swift
  Peekabook/Peekabook/Presentation/BookShelf/Views/CVC/BookShelfCVC.swift
  Peekabook/Peekabook/Presentation/BookShelf/Views/CVC/FriendsCVC.swift
  Peekabook/Peekabook/Presentation/BookShelf/Views/CVC/PickCVC.swift
Labels: 수빈 💭, API 📡

#83 [Feat] #80 - 책 상세보기 api 연결
  Peekabook/Peekabook.xcodeproj/project.pbxproj
  Peekabook/Peekabook/Network/API/BookShelfAPI.swift
  Peekabook/Peekabook/Network/DTO/BookShelf/WatchBookDetailResponse.swift
  Peekabook/Peekabook/Network/Foundation/URLConstant.swift
  Peekabook/Peekabook/Network/Router/BookShelfRouter.swift
  Peekabook/Peekabook/Presentation/BookDetail/VC/BookDetailVC.swift
  Peekabook/Peekabook/Presentation/BookShelf/VC/BookShelfVC.swift
Labels: 두영 🐱, API 📡

#87 [Feat] #82 - 추천받은 책, 추천한 책 뷰 api 연결
  Peekabook/Peekabook.xcodeproj/project.pbxproj
  Peekabook/Peekabook/Network/API/RecommendAPI.swift
  Peekabook/Peekabook/Network/DTO/Recommend/GetRecommendResponse.swift
  Peekabook/Peekabook/Network/Router/RecommendRouter.swift
  Peekabook/Peekabook/Presentation/Recommend/VC/RecommendedVC.swift
  Peekabook/Peekabook/Presentation/Recommend/VC/RecommendingVC.swift
  Peekabook/Peekabook/Presentation/Recommend/Views/RecommendTVC.swift
Labels: 인영 🧸, API 📡

#91 [Chore] #90- Router Request Header 필요하도록 수정
  Peekabook/Peekabook/Network/Foundation/NetworkConstant.swift
  Peekabook/Peekabook/Network/Router/AlarmRouter.swift
  Peekabook/Peekabook/Network/Router/BookShelfRouter.swift
  Peekabook/Peekabook/Network/Router/FriendRouter.swift
  Peekabook/Peekabook/Network/Router/PickRouter.swift
  Peekabook/Peekabook/Network/Router/RecommendRouter.swift
  Peekabook/Peekabook/Presentation/BookShelf/VC/BookShelfVC.swift
Labels: Setting ⚙️, API 📡

#94 [Feat] #85 - 책 상세보기 API 연결
  Peekabook/Peekabook/Presentation/BookDetail/VC/BookDetailVC.swift
  Peekabook/Peekabook/Presentation/BookShelf/VC/BookShelfVC.swift
  Peekabook/Peekabook/Presentation/BookShelf/VC/BottomBookShelfVC.swift
Labels: 두영 🐱, API 📡

#96 [Chore] #92 - 추천탭 뷰 레이아웃 수정
  Peekabook/Peekabook/Presentation/Recommend/VC/RecommendedVC.swift
  Peekabook/Peekabook/Presentation/Recommend/VC/RecommendingVC.swift
  Peekabook/Peekabook/Presentation/Recommend/Views/RecommendCVC.swift
  Peekabook/Peekabook/Presentation/Recommend/Views/RecommendTVC.swift
Labels: 인영 🧸, Design 🎨

#102 [Fix] #99- BookShelf Response 변경 대응
  Peekabook/Peekabook/Network/DTO/BookShelf/MyBookShelfResponse.swift
  Peekabook/Peekabook/Network/DTO/BookShelf/WatchBookDetailResponse.swift
  Peekabook/Peekabook/Presentation/BookShelf/VC/BookShelfVC.swift
  Peekabook/Peekabook/Presentation/BookShelf/Views/CVC/BookShelfCVC.swift
  Peekabook/Peekabook/Presentation/BookShelf/Views/CVC/FriendsCVC.swift
Labels: 수빈 💭, Fix ✨

#97 [Feat] #88- 팔로우 취소 api 연결
  Peekabook/Peekabook/Network/API/FriendAPI.swift
  Peekabook/Peekabook/Network/Router/FriendRouter.swift
  Peekabook/Peekabook/Presentation/BookShelf/VC/BookShelfVC.swift
  Peekabook/Peekabook/Presentation/UserSearch/VC/UserSearchVC.swift
Labels: 인영 🧸, API 📡

#104 [Feat] #86 - Pick 수정 뷰 전체 조회 API 연결
  Peekabook/Peekabook.xcodeproj/project.pbxproj
  Peekabook/Peekabook/Network/API/PickAPI.swift
  Peekabook/Peekabook/Network/DTO/Alarm/.gitkeep
  Peekabook/Peekabook/Network/DTO/Friend/.gitkeep
  Peekabook/Peekabook/Network/DTO/Pick/.gitkeep
  Peekabook/Peekabook/Network/DTO/Pick/PickAllResponse.swift
  Peekabook/Peekabook/Network/DTO/Recommend/.gitkeep
  Peekabook/Peekabook/Network/Router/PickRouter.swift
  Peekabook/Peekabook/Presentation/BookDetail/VC/EditBookVC.swift
  Peekabook/Peekabook/Presentation/EditMyPick/VC/EditMyPickVC.swift
  Peekabook/Peekabook/Presentation/EditMyPick/Views/CVC/EditPickCVC.swift
Labels: 수빈 💭, API 📡

#107 [Feat]#98- 책 삭제 api 구현
  Peekabook/Peekabook.xcodeproj/project.pbxproj
  Peekabook/Peekabook/Global/Literals/StringLiterals.swift
  Peekabook/Peekabook/Network/API/BookShelfAPI.swift
  Peekabook/Peekabook/Network/Router/BookShelfRouter.swift
  Peekabook/Peekabook/Presentation/BookDetail/VC/BookDetailVC.swift
  Peekabook/Peekabook/Presentation/BookDetail/VC/DeletePopUpVC.swift
Labels: 인영 🧸, Design 🎨, API 📡

#109 [Feat] #70 - 네이버 API 책 텍스트검색 연결
  Peekabook/Peekabook.xcodeproj/project.pbxproj
  Peekabook/Peekabook/Network/API/NaverSearchAPI.swift
  Peekabook/Peekabook/Network/DTO/NaverSearch/NaverSearchResponse.swift
  Peekabook/Peekabook/Presentation/AddBook/Model/BookInfoModel.swift
  Peekabook/Peekabook/Presentation/AddBook/VC/AddBookVC.swift
  Peekabook/Peekabook/Presentation/AddBook/VC/BarcodeViewController.swift
  Peekabook/Peekabook/Presentation/AddBook/VC/BookInfoTableViewCell.swift
  Peekabook/Peekabook/Presentation/AddBook/VC/BookSearchVC.swift
Labels: 두영 🐱, API 📡

#112 [Feat] - 네이버 ISBN 책 검색 API 연결
  Peekabook/Peekabook/Network/API/NaverSearchAPI.swift
  Peekabook/Peekabook/Presentation/AddBook/VC/AddBookVC.swift
  Peekabook/Peekabook/Presentation/AddBook/VC/BarcodeViewController.swift
  Peekabook/Peekabook/Presentation/AddBook/VC/BookSearchVC.swift
Labels: 두영 🐱, API 📡

#114 [Feat] #89- 사용자 알림 api 연결
  Peekabook/Peekabook.xcodeproj/project.pbxproj
  Peekabook/Peekabook/Global/Literals/StringLiterals.swift
  Peekabook/Peekabook/Network/API/AlarmAPI.swift
  Peekabook/Peekabook/Network/DTO/Alarm/GetAlarmResponse.swift
  Peekabook/Peekabook/Network/Router/AlarmRouter.swift
  Peekabook/Peekabook/Presentation/MyNotification/VC/MyNotificationVC.swift
  Peekabook/Peekabook/Presentation/MyNotification/Views/MyNotificationTVC.swift
Labels: 인영 🧸, API 📡

#115 [Feat] #105 - PICK 수정하기 API 연결
  Peekabook/Peekabook.xcodeproj/project.pbxproj
  Peekabook/Peekabook/Global/Literals/ImageLiterals.swift
  Peekabook/Peekabook/Global/Literals/StringLiterals.swift
  Peekabook/Peekabook/Global/Resources/Assets.xcassets/icons/icn_newPick.imageset/Contents.json
  Peekabook/Peekabook/Global/Resources/Assets.xcassets/icons/icn_newPick.imageset/icn_newPick.png
  Peekabook/Peekabook/Global/Resources/Assets.xcassets/icons/icn_newPick.imageset/icn_newPick@2x.png
  Peekabook/Peekabook/Global/Resources/Assets.xcassets/icons/icn_newPick.imageset/icn_newPick@3x.png
  Peekabook/Peekabook/Network/API/BookShelfAPI.swift
  Peekabook/Peekabook/Network/API/FriendAPI.swift
  Peekabook/Peekabook/Network/API/PickAPI.swift
  Peekabook/Peekabook/Network/DTO/Alarm/.gitkeep
  Peekabook/Peekabook/Network/DTO/Pick/EditPickRequest.swift
  Peekabook/Peekabook/Network/Router/BookShelfRouter.swift
  Peekabook/Peekabook/Network/Router/FriendRouter.swift
  Peekabook/Peekabook/Network/Router/PickRouter.swift
  Peekabook/Peekabook/Network/Router/RecommendRouter.swift
  Peekabook/Peekabook/Presentation/BookDetail/VC/EditBookVC.swift
  Peekabook/Peekabook/Presentation/BookShelf/VC/BookShelfVC.swift
  Peekabook/Peekabook/Presentation/BookShelf/Views/CVC/BookShelfCVC.swift
  Peekabook/Peekabook/Presentation/BookShelf/Views/CVC/PickCVC.swift
  Peekabook/Peekabook/Presentation/EditMyPick/VC/EditMyPickVC.swift
  Peekabook/Peekabook/Presentation/EditMyPick/Views/CVC/EditPickCVC.swift
  Peekabook/Peekabook/Presentation/UserSearch/VC/UserSearchVC.swift
Labels: 수빈 💭, API 📡

#117 [Fix] #106- getAlarmResponse 프로젝트 파일 경로 문제 해제
  Peekabook/Peekabook.xcodeproj/project.pbxproj
Labels: Fix ✨

#119 [Fix] #118- GetAlarmResponse 파일 제거
  Peekabook/Peekabook.xcodeproj/project.pbxproj
Labels: 수빈 💭, Fix ✨

#121 [Chore] #108- 유저, 친구 타입에 따른 레이아웃 변경 코드 추가
  Peekabook/Peekabook/Presentation/BookDetail/VC/BookDetailVC.swift
  Peekabook/Peekabook/Presentation/BookShelf/VC/BookShelfVC.swift
Labels: 수빈 💭, Design 🎨

#125 [Fix] #101 - 친구 책 상세보기 API 연결
  Peekabook/Peekabook/Global/Literals/StringLiterals.swift
  Peekabook/Peekabook/Network/API/BookShelfAPI.swift
  Peekabook/Peekabook/Network/DTO/BookShelf/MyBookShelfResponse.swift
  Peekabook/Peekabook/Network/DTO/BookShelf/WatchBookDetailResponse.swift
  Peekabook/Peekabook/Network/Router/BookShelfRouter.swift
  Peekabook/Peekabook/Presentation/AddBook/VC/AddBookVC.swift
  Peekabook/Peekabook/Presentation/AddBook/VC/BookInfoTableViewCell.swift
  Peekabook/Peekabook/Presentation/BookDetail/VC/BookDetailVC.swift
  Peekabook/Peekabook/Presentation/BookDetail/VC/DeletePopUpVC.swift
  Peekabook/Peekabook/Presentation/BookShelf/VC/BookShelfVC.swift
  Peekabook/Peekabook/Presentation/BookShelf/VC/BottomBookShelfVC.swift
  Peekabook/Peekabook/Presentation/BookShelf/Views/CVC/BookShelfCVC.swift
  Peekabook/Peekabook/Presentation/BookShelf/Views/CVC/FriendsCVC.swift
  Peekabook/Peekabook/Presentation/BookShelf/Views/CVC/PickCVC.swift
  Peekabook/Peekabook/Presentation/EditMyPick/VC/EditMyPickVC.swift
  Peekabook/Peekabook/Presentation/EditMyPick/Views/CVC/EditPickCVC.swift
  Peekabook/Peekabook/Presentation/MyNotification/Views/MyNotificationTVC.swift
  Peekabook/Peekabook/Presentation/Recommend/Views/RecommendTVC.swift
  Peekabook/Peekabook/Presentation/UserSearch/VC/UserSearchVC.swift
Labels: 수빈 💭, Design 🎨, API 📡

#127 [Chore] #126- 사용자 검색 키보드 이벤트 추가
  Peekabook/Peekabook/Presentation/UserSearch/VC/UserSearchVC.swift
Labels: 인영 🧸, Design 🎨

#129 [Fix] #124 - QA 반영
  Peekabook/Peekabook/Global/Literals/StringLiterals.swift
  Peekabook/Peekabook/Presentation/AddBook/VC/AddBookVC.swift
  Peekabook/Peekabook/Presentation/AddBook/VC/BookSearchVC.swift
  Peekabook/Peekabook/Presentation/BookDetail/VC/EditBookVC.swift
  Peekabook/Peekabook/Presentation/BookShelf/VC/BookShelfVC.swift
  Peekabook/Peekabook/Presentation/Proposal/VC/ProposalVC.swift
Labels: 두영 🐱, Refactor 🔨, Design 🎨, Fix ✨

#133 [Fix] #132 - 네이버 검색 삐슝빠슝 이슈 해결
  Peekabook/Peekabook/Network/API/NaverSearchAPI.swift
  Peekabook/Peekabook/Presentation/AddBook/VC/AddBookVC.swift
  Peekabook/Peekabook/Presentation/AddBook/VC/BookSearchVC.swift
  Peekabook/Peekabook/Presentation/BookShelf/VC/BookShelfVC.swift
  Peekabook/Peekabook/Presentation/Proposal/VC/ProposalVC.swift
Labels: 수빈 💭, API 📡, Fix ✨

#134 [Fix] #131 - QA 반영
  Peekabook/Peekabook.xcodeproj/project.pbxproj
  Peekabook/Peekabook/Presentation/AddBook/VC/AddBookVC.swift
  Peekabook/Peekabook/Presentation/AddBook/VC/BookInfoTableViewCell.swift
Labels: 두영 🐱, Fix ✨

#135 [Fix] #128 - 레이아웃 수정
  Peekabook/Peekabook/Presentation/AddBook/VC/BarcodeViewController.swift
  Peekabook/Peekabook/Presentation/AddBook/VC/BookSearchVC.swift
Labels: 두영 🐱, Design 🎨

#137 [Feat] #123- 친구에게 책 추천 API 연결
  Peekabook/Peekabook.xcodeproj/project.pbxproj
  Peekabook/Peekabook/Network/API/FriendAPI.swift
  Peekabook/Peekabook/Network/DTO/Friend/ProposalBookRequest.swift
  Peekabook/Peekabook/Network/Router/FriendRouter.swift
  Peekabook/Peekabook/Presentation/AddBook/VC/BookInfoTableViewCell.swift
  Peekabook/Peekabook/Presentation/AddBook/VC/BookSearchVC.swift
  Peekabook/Peekabook/Presentation/BookShelf/VC/BookShelfVC.swift
  Peekabook/Peekabook/Presentation/Proposal/VC/ConfirmPopUpViewController.swift
  Peekabook/Peekabook/Presentation/Proposal/VC/ProposalVC.swift
  Peekabook/Peekabook/Presentation/TabBar/TabBarController.swift
Labels: 수빈 💭, API 📡

#139 [Chore] #128- 팔로잉 여부에 따라 테두리 색 변화
  Peekabook/Peekabook/Presentation/UserSearch/VC/UserSearchVC.swift
Labels: 인영 🧸, Design 🎨

#144 [Feat] #136 - 책 정보 수정 API
  Peekabook/Peekabook.xcodeproj/project.pbxproj
  Peekabook/Peekabook/Network/API/BookShelfAPI.swift
  Peekabook/Peekabook/Network/DTO/BookShelf/EditBookRequest.swift
  Peekabook/Peekabook/Network/Router/BookShelfRouter.swift
  Peekabook/Peekabook/Presentation/AddBook/VC/AddBookVC.swift
  Peekabook/Peekabook/Presentation/AddBook/VC/BookSearchVC.swift
  Peekabook/Peekabook/Presentation/BookDetail/VC/BookDetailVC.swift
  Peekabook/Peekabook/Presentation/BookDetail/VC/EditBookVC.swift
  Peekabook/Peekabook/Presentation/EditMyPick/VC/EditMyPickVC.swift
Labels: 두영 🐱, API 📡

#146 [Refactor] #145 - 코드리팩토링
  Peekabook/.swiftlint.yml
  Peekabook/Peekabook.xcodeproj/project.pbxproj
  Peekabook/Peekabook/Global/Utils/showToastMessage.swift
  Peekabook/Peekabook/Global/Utils/switchRootViewController.swift
  Peekabook/Peekabook/Network/API/NaverSearchAPI.swift
  Peekabook/Peekabook/Network/API/PickAPI.swift
  Peekabook/Peekabook/Network/Config/.gitkeep
  Peekabook/Peekabook/Network/DTO/NaverSearch/NaverSearchResponse.swift
  Peekabook/Peekabook/Network/Foundation/URLConstant.swift
  Peekabook/Peekabook/Network/Router/FriendRouter.swift
  Peekabook/Peekabook/Presentation/AddBook/VC/AddBookVC.swift
  Peekabook/Peekabook/Presentation/AddBook/VC/BarcodeViewController.swift
  Peekabook/Peekabook/Presentation/AddBook/VC/BookEmptyViewController.swift
  Peekabook/Peekabook/Presentation/AddBook/VC/BookInfoTableViewCell.swift
  Peekabook/Peekabook/Presentation/AddBook/VC/BookSearchVC.swift
  Peekabook/Peekabook/Presentation/AddBook/Views/BookInfoTableViewCell.swift
  Peekabook/Peekabook/Presentation/BookDetail/VC/BookDetailVC.swift
  Peekabook/Peekabook/Presentation/BookDetail/VC/DeletePopUpVC.swift
  Peekabook/Peekabook/Presentation/BookDetail/VC/EditBookVC.swift
  Peekabook/Peekabook/Presentation/BookShelf/Model/SampleBookModel.swift
  Peekabook/Peekabook/Presentation/BookShelf/Model/SampleFriendsModel.swift
  Peekabook/Peekabook/Presentation/BookShelf/Model/SamplePickModel.swift
  Peekabook/Peekabook/Presentation/BookShelf/Model/SampleUserModel.swift
  Peekabook/Peekabook/Presentation/BookShelf/VC/BookShelfVC.swift
  Peekabook/Peekabook/Presentation/BookShelf/VC/BottomBookShelfVC.swift
  Peekabook/Peekabook/Presentation/BookShelf/Views/CVC/BookShelfCVC.swift
  Peekabook/Peekabook/Presentation/BookShelf/Views/CVC/FriendsCVC.swift
  Peekabook/Peekabook/Presentation/BookShelf/Views/CVC/PickCVC.swift
  Peekabook/Peekabook/Presentation/EditMyPick/Model/SampleEditPickModel.swift
  Peekabook/Peekabook/Presentation/EditMyPick/VC/EditMyPickVC.swift
  Peekabook/Peekabook/Presentation/EditMyPick/Views/CVC/EditPickCVC.swift
  Peekabook/Peekabook/Presentation/MyNotification/VC/MyNotificationVC.swift
  Peekabook/Peekabook/Presentation/MyNotification/Views/.gitkeep
  Peekabook/Peekabook/Presentation/MyNotification/Views/MyNotificationTVC.swift
  Peekabook/Peekabook/Presentation/MyPage/VC/MyPageVC.swift
  Peekabook/Peekabook/Presentation/MyPage/Views/.gitkeep
  Peekabook/Peekabook/Presentation/MyPage/Views/MyPageHeaderView.swift
  Peekabook/Peekabook/Presentation/MyPage/Views/MyPageTableViewCell.swift
  Peekabook/Peekabook/Presentation/Proposal/VC/ConfirmPopUpViewController.swift
  Peekabook/Peekabook/Presentation/Proposal/VC/ProposalVC.swift
  Peekabook/Peekabook/Presentation/Proposal/Views/.gitkeep
  Peekabook/Peekabook/Presentation/Proposal/Views/.gitkeep.md
  Peekabook/Peekabook/Presentation/Proposal/Views/.gitkeep.xib
  Peekabook/Peekabook/Presentation/Recommend/VC/RecommendVC.swift
  Peekabook/Peekabook/Presentation/Recommend/VC/RecommendedVC.swift
  Peekabook/Peekabook/Presentation/Recommend/VC/RecommendingVC.swift
  Peekabook/Peekabook/Presentation/Recommend/Views/.gitkeep
  Peekabook/Peekabook/Presentation/Recommend/Views/RecommendCVC.swift
  Peekabook/Peekabook/Presentation/UserSearch/VC/UserSearchVC.swift
Labels: 수빈 💭, Refactor 🔨

#149 [Chore] #148- 프로젝트 파일 경로 수정
  Peekabook/Peekabook.xcodeproj/project.pbxproj
Labels: 수빈 💭, Setting ⚙️
