Repository team-peekabook/Peekabook-iOS, pull requests merged in 2023-03, with the labels that each got.

#160 [Refactor] #159 컴포넌트화, Moya로 수정 등 리팩토링
  Peekabook/Peekabook.xcodeproj/project.pbxproj
  Peekabook/Peekabook.xcodeproj/xcshareddata/xcschemes/Peekabook.xcscheme
  Peekabook/Peekabook/Global/Literals/StringLiterals.swift
  Peekabook/Peekabook/Network/API/NaverSearchAPI.swift
  Peekabook/Peekabook/Network/DTO/NaverSearch/.gitkeep
  Peekabook/Peekabook/Network/DTO/NaverSearch/NaverSearchResponse.swift
  Peekabook/Peekabook/Network/Router/NaverSearchRouter.swift
  Peekabook/Peekabook/Presentation/AddBook/VC/AddBookVC.swift
  Peekabook/Peekabook/Presentation/AddBook/VC/BarcodeVC.swift
  Peekabook/Peekabook/Presentation/AddBook/VC/BookSearchVC.swift
  Peekabook/Peekabook/Presentation/AddBook/Views/BookInfoTVC.swift
  Peekabook/Peekabook/Presentation/BookDetail/VC/BookDetailVC.swift
  Peekabook/Peekabook/Presentation/BookDetail/VC/EditBookVC.swift
  Peekabook/Peekabook/Presentation/BookDetail/VC/TestModel.swift
  Peekabook/Peekabook/Presentation/Proposal/VC/ProposalVC.swift
  Peekabook/Peekabook/Presentation/UIComponents/CustomSearchView.swift
  Peekabook/Peekabook/Presentation/UIComponents/CustomTextView.swift
  Peekabook/Peekabook/Presentation/UserSearch/VC/UserSearchVC.swift
Labels: 두영 🐱, Refactor 🔨

#164 Refactor/#163 팝업뷰 코드 리팩토링
  Peekabook/Peekabook.xcodeproj/project.pbxproj
  Peekabook/Peekabook/Presentation/AddBook/VC/ErrorPopUpVC.swift
  Peekabook/Peekabook/Presentation/BookDetail/VC/DeletePopUpVC.swift
  Peekabook/Peekabook/Presentation/Proposal/VC/ConfirmPopUpVC.swift
  Peekabook/Peekabook/Presentation/UIComponents/CustomPopUpView.swift
Labels: 인영 🧸, Refactor 🔨

#166 [Refactor] #147- 리팩토링
  Peekabook/Peekabook.xcodeproj/project.pbxproj
  Peekabook/Peekabook/Global/Extension/Array+.swift
  Peekabook/Peekabook/Global/Extension/UIScreen+.swift
  Peekabook/Peekabook/Global/Extension/UITextField+.swift
  Peekabook/Peekabook/Global/Extension/addPadding+UITextField.swift
  Peekabook/Peekabook/Presentation/AddBook/VC/AddBookVC.swift
  Peekabook/Peekabook/Presentation/AddBook/VC/BookSearchVC.swift
  Peekabook/Peekabook/Presentation/AddBook/VC/ErrorPopUpVC.swift
  Peekabook/Peekabook/Presentation/BookShelf/VC/BookShelfVC.swift
  Peekabook/Peekabook/Presentation/BookShelf/VC/BottomBookShelfVC.swift
  Peekabook/Peekabook/Presentation/BookShelf/Views/CVC/BookShelfCVC.swift
  Peekabook/Peekabook/Presentation/BookShelf/Views/CVC/FriendsCVC.swift
  Peekabook/Peekabook/Presentation/BookShelf/Views/CVC/PickCVC.swift
  Peekabook/Peekabook/Presentation/EditMyPick/VC/EditMyPickVC.swift
  Peekabook/Peekabook/Presentation/EditMyPick/Views/CVC/EditPickCVC.swift
  Peekabook/Peekabook/Presentation/MyNotification/VC/MyNotificationVC.swift
  Peekabook/Peekabook/Presentation/MyPage/VC/MyPageVC.swift
  Peekabook/Peekabook/Presentation/Recommend/VC/RecommendedVC.swift
  Peekabook/Peekabook/Presentation/Recommend/VC/RecommendingVC.swift
  Peekabook/Peekabook/Presentation/UIComponents/CustomNavigationBar.swift
  Peekabook/Peekabook/Presentation/UIComponents/DoubleBottomLineView.swift
  Peekabook/Peekabook/Presentation/UIComponents/DoubleHeaderLineView.swift
  Peekabook/Peekabook/Presentation/UIComponents/SingleTouchButton.swift
Labels: 수빈 💭, Refactor 🔨

#165 [Refactor] #162 - 에러 해결
  Peekabook/Peekabook.xcodeproj/project.pbxproj
  Peekabook/Peekabook/Global/Literals/StringLiterals.swift
  Peekabook/Peekabook/Network/API/NaverSearchAPI.swift
  Peekabook/Peekabook/Network/DTO/NaverSearch/NaverSearchResponse.swift
  Peekabook/Peekabook/Presentation/AddBook/VC/AddBookVC.swift
  Peekabook/Peekabook/Presentation/AddBook/VC/BarcodeVC.swift
  Peekabook/Peekabook/Presentation/AddBook/VC/BookSearchVC.swift
  Peekabook/Peekabook/Presentation/AddBook/Views/BookInfoTVC.swift
  Peekabook/Peekabook/Presentation/BookDetail/VC/BookDetailVC.swift
  Peekabook/Peekabook/Presentation/BookDetail/VC/EditBookVC.swift
  Peekabook/Peekabook/Presentation/BookDetail/VC/TestModel.swift
  Peekabook/Peekabook/Presentation/Proposal/VC/ProposalVC.swift
  Peekabook/Peekabook/Presentation/UIComponents/CustomSearchView.swift
  Peekabook/Peekabook/Presentation/UIComponents/CustomTextView.swift
  Peekabook/Peekabook/Presentation/UserSearch/VC/UserSearchVC.swift
Labels: 두영 🐱, Refactor 🔨

#168 [Refactor] #152 - 추천탭 뷰 리팩토링
  Peekabook/Peekabook.xcodeproj/project.pbxproj
  Peekabook/Peekabook/Presentation/Recommend/Model/RecommendModel.swift
  Peekabook/Peekabook/Presentation/Recommend/VC/RecommendVC.swift
  Peekabook/Peekabook/Presentation/Recommend/VC/RecommendedVC.swift
  Peekabook/Peekabook/Presentation/Recommend/VC/RecommendingVC.swift
  Peekabook/Peekabook/Presentation/Recommend/Views/RecommendListTVC.swift
  Peekabook/Peekabook/Presentation/Recommend/Views/RecommendTypeCVC.swift
Labels: 인영 🧸, Refactor 🔨

#173 [Refator] #171 - 커스텀뷰 리팩토링
  Peekabook/Peekabook/Presentation/AddBook/VC/AddBookVC.swift
  Peekabook/Peekabook/Presentation/AddBook/VC/BookSearchVC.swift
  Peekabook/Peekabook/Presentation/BookDetail/VC/BookDetailVC.swift
  Peekabook/Peekabook/Presentation/BookDetail/VC/EditBookVC.swift
  Peekabook/Peekabook/Presentation/Proposal/VC/ProposalVC.swift
  Peekabook/Peekabook/Presentation/UIComponents/CustomSearchView.swift
  Peekabook/Peekabook/Presentation/UIComponents/CustomTextView.swift
  Peekabook/Peekabook/Presentation/UserSearch/VC/UserSearchVC.swift
Labels: 두영 🐱, Refactor 🔨

#172 [Chore] #170 - 책 등록시 출판사 추가
  Peekabook/Peekabook/Network/DTO/BookShelf/PostBookRequest.swift
  Peekabook/Peekabook/Network/DTO/NaverSearch/NaverSearchResponse.swift
  Peekabook/Peekabook/Presentation/AddBook/VC/AddBookVC.swift
  Peekabook/Peekabook/Presentation/AddBook/VC/BarcodeVC.swift
  Peekabook/Peekabook/Presentation/AddBook/VC/BookSearchVC.swift
Labels: 인영 🧸, API 📡

#177 [Fix] #176 - 바코드 스캔 이슈 해결
  Peekabook/Peekabook/Presentation/AddBook/VC/BarcodeVC.swift
Labels: 두영 🐱, Fix ✨

#175 [Refactor] #174 - 커스텀 네비바 적용
  Peekabook/Peekabook/Presentation/AddBook/VC/AddBookVC.swift
  Peekabook/Peekabook/Presentation/BookDetail/VC/BookDetailVC.swift
  Peekabook/Peekabook/Presentation/BookDetail/VC/EditBookVC.swift
  Peekabook/Peekabook/Presentation/BookShelf/VC/BookShelfVC.swift
  Peekabook/Peekabook/Presentation/BookShelf/VC/BottomBookShelfVC.swift
  Peekabook/Peekabook/Presentation/Proposal/VC/ProposalVC.swift
  Peekabook/Peekabook/Presentation/UIComponents/CustomNavigationBar.swift
Labels: 두영 🐱, Refactor 🔨

#181 [Fix] #179 - 책 추천 데이터 안 넘어옴 에러해결
  Peekabook/Peekabook/Network/DTO/Friend/ProposalBookRequest.swift
  Peekabook/Peekabook/Presentation/Proposal/VC/ConfirmPopUpVC.swift
  Peekabook/Peekabook/Presentation/Proposal/VC/ProposalVC.swift
Labels: 인영 🧸, Fix ✨

#178 [Refactor] #169 - 커스텀 네비바 적용
  Peekabook/Peekabook.xcodeproj/project.pbxproj
  Peekabook/Peekabook/Global/Literals/ImageLiterals.swift
  Peekabook/Peekabook/Presentation/AddBook/VC/AddBookVC.swift
  Peekabook/Peekabook/Presentation/AddBook/VC/BarcodeVC.swift
  Peekabook/Peekabook/Presentation/AddBook/VC/BookSearchVC.swift
  Peekabook/Peekabook/Presentation/MyNotification/VC/MyNotificationVC.swift
  Peekabook/Peekabook/Presentation/MyPage/VC/MyPageVC.swift
  Peekabook/Peekabook/Presentation/MyPage/Views/MyPageHeaderView.swift
  Peekabook/Peekabook/Presentation/MyPage/Views/MyPageTableViewCell.swift
  Peekabook/Peekabook/Presentation/Recommend/VC/RecommendVC.swift
  Peekabook/Peekabook/Presentation/UIComponents/CustomNavigationBar.swift
  Peekabook/Peekabook/Presentation/UIComponents/CustomPopUpView.swift
  Peekabook/Peekabook/Presentation/UIComponents/CustomSearchView.swift
  Peekabook/Peekabook/Presentation/UserSearch/Model/UserSearchModel.swift
  Peekabook/Peekabook/Presentation/UserSearch/VC/UserSearchVC.swift
Labels: 인영 🧸, Refactor 🔨

#182 [Fix] #180 - 플레이스홀더 이슈 해결
  Peekabook/Peekabook/Presentation/AddBook/VC/AddBookVC.swift
  Peekabook/Peekabook/Presentation/BookDetail/VC/EditBookVC.swift
  Peekabook/Peekabook/Presentation/UIComponents/CustomTextView.swift
Labels: 두영 🐱, Fix ✨

#184 [Chore] #183- 책장 뷰, 픽 수정뷰 Then 라이브러리 제거
  Peekabook/Peekabook.xcodeproj/project.pbxproj
  Peekabook/Peekabook/Peekabook.entitlements
  Peekabook/Peekabook/Presentation/BookShelf/VC/BookShelfVC.swift
  Peekabook/Peekabook/Presentation/BookShelf/VC/BottomBookShelfVC.swift
  Peekabook/Peekabook/Presentation/BookShelf/Views/CVC/BookShelfCVC.swift
  Peekabook/Peekabook/Presentation/BookShelf/Views/CVC/FriendsCVC.swift
  Peekabook/Peekabook/Presentation/BookShelf/Views/CVC/PickCVC.swift
  Peekabook/Peekabook/Presentation/EditMyPick/VC/EditMyPickVC.swift
  Peekabook/Peekabook/Presentation/EditMyPick/Views/CVC/EditPickCVC.swift
Labels: 수빈 💭, Refactor 🔨

#188 [Feat] #186 - 케밥버튼, 신고하기 뷰 레이아웃
  Peekabook/Peekabook.xcodeproj/project.pbxproj
  Peekabook/Peekabook/Global/Literals/ImageLiterals.swift
  Peekabook/Peekabook/Global/Literals/StringLiterals.swift
  Peekabook/Peekabook/Global/Resources/Assets.xcassets/icons/icn_more.imageset/Contents.json
  Peekabook/Peekabook/Global/Resources/Assets.xcassets/icons/icn_more.imageset/icn_more.png
  Peekabook/Peekabook/Global/Resources/Assets.xcassets/icons/icn_more.imageset/icn_more@2x.png
  Peekabook/Peekabook/Global/Resources/Assets.xcassets/icons/icn_more.imageset/icn_more@3x.png
  Peekabook/Peekabook/Global/Resources/Assets.xcassets/icons/icn_radio_button_checked.imageset/Contents.json
  Peekabook/Peekabook/Global/Resources/Assets.xcassets/icons/icn_radio_button_checked.imageset/icn_radio_button_checked.png
  Peekabook/Peekabook/Global/Resources/Assets.xcassets/icons/icn_radio_button_checked.imageset/icn_radio_button_checked@2x.png
  Peekabook/Peekabook/Global/Resources/Assets.xcassets/icons/icn_radio_button_checked.imageset/icn_radio_button_checked@3x.png
  Peekabook/Peekabook/Global/Resources/Assets.xcassets/icons/icn_radio_button_unchecked.imageset/Contents.json
  Peekabook/Peekabook/Global/Resources/Assets.xcassets/icons/icn_radio_button_unchecked.imageset/icn_radio_button_unchecked.png
  Peekabook/Peekabook/Global/Resources/Assets.xcassets/icons/icn_radio_button_unchecked.imageset/icn_radio_button_unchecked@2x.png
  Peekabook/Peekabook/Global/Resources/Assets.xcassets/icons/icn_radio_button_unchecked.imageset/icn_radio_button_unchecked@3x.png
  Peekabook/Peekabook/Presentation/BookShelf/VC/BookShelfVC.swift
  Peekabook/Peekabook/Presentation/UserDeclare/VC/ReportVC.swift
  Peekabook/Peekabook/Presentation/UserDeclare/Views/ReportTVC.swift
Labels: 두영 🐱, Design 🎨

#190 [Feat] #189 - 팝업뷰 레이아웃
  Peekabook/Peekabook.xcodeproj/project.pbxproj
  Peekabook/Peekabook/Global/Literals/ImageLiterals.swift
  Peekabook/Peekabook/Global/Literals/StringLiterals.swift
  Peekabook/Peekabook/Global/Resources/Assets.xcassets/icons/icn_delete_account.imageset/Contents.json
  Peekabook/Peekabook/Global/Resources/Assets.xcassets/icons/icn_delete_account.imageset/icn_delete_account.png
  Peekabook/Peekabook/Global/Resources/Assets.xcassets/icons/icn_delete_account.imageset/icn_delete_account@2x.png
  Peekabook/Peekabook/Global/Resources/Assets.xcassets/icons/icn_delete_account.imageset/icn_delete_account@3x.png
  Peekabook/Peekabook/Presentation/BookShelf/VC/BlockPopUpVC.swift
  Peekabook/Peekabook/Presentation/BookShelf/VC/DeclarePopUpVC.swift
  Peekabook/Peekabook/Presentation/BookShelf/VC/UnfollowPopUpVC.swift
  Peekabook/Peekabook/Presentation/MyPage/VC/DeleteAccountPopUpVC.swift
  Peekabook/Peekabook/Presentation/MyPage/VC/DeleteAccountVC.swift
  Peekabook/Peekabook/Presentation/MyPage/VC/LogoutPopUpVC.swift
  Peekabook/Peekabook/Presentation/MyPage/VC/MyPageVC.swift
  Peekabook/Peekabook/Presentation/MyPage/Views/MyPageTableViewCell.swift
  Peekabook/Peekabook/Presentation/UIComponents/CustomPopUpView.swift
Labels: 두영 🐱, Design 🎨

#199 [Hotfix] #198- String Literals 에러 해결
  Peekabook/Peekabook/Global/Literals/StringLiterals.swift
Labels: 두영 🐱, Fix ✨

#196 [Feat] #193- 차단 사용자 관리 뷰 레이아웃 구현
  Peekabook/Peekabook.xcodeproj/project.pbxproj
  Peekabook/Peekabook/Global/Literals/StringLiterals.swift
  Peekabook/Peekabook/Presentation/MyPage/VC/ManageBlockUsersVC.swift
  Peekabook/Peekabook/Presentation/MyPage/VC/MyPageVC.swift
  Peekabook/Peekabook/Presentation/MyPage/VC/UnblockPopUpVC.swift
  Peekabook/Peekabook/Presentation/MyPage/Views/BlockedUserCVC.swift
  Peekabook/Peekabook/Presentation/MyPage/Views/MyPageTVC.swift
  Peekabook/Peekabook/Presentation/UIComponents/CustomPopUpView.swift
Labels: 수빈 🤍, Design 🎨
